### ISSUE TITLE
I received a new iPhone. After switched from my old device (one red warning) to my new one by using apples built in transfer setting functionality I found zero exposure tracings ending up in a green status. It should be possible to copy exposure tracking tickets from one device to another new one otherwise we will have a gap in the tracing.

### ISSUE THREAD

**Issue by AH0404** [corona-warn-app/cwa-app-ios#4112]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

**Comment by Ein-Tim** [comment]
Hi @AH0404

Please take a look at https://www.coronawarn.app/en/faq/#new_device.

A related issue here on GitHub is:
- https://github.com/corona-warn-app/cwa-wishlist/issues/8

**Comment by Ein-Tim** [comment]
@dsarkar I think this can be closed.

**Comment by Ein-Tim** [comment]
Can this issue be closed?

**Comment by dsarkar** [comment]
Good morning @AH0404, thanks for contributing here. Your question has been answered, therefore we are closing this issue now. Should you have more question, suggestions, or a bug to report, etc, please don't hesitate opening a new issue. Thanks again. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar Don't forget to press the "Close" button :D
